=== api-evangelist/airbus-oneatlas/json-schema/oneatlas-segment-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/airbus-oneatlas/refs/heads/main/json-schema/oneatlas-segment-schema.json",
  "title": "segment",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "footprint": {
      "$ref": "#/components/schemas/footprint"
    },
    "instrumentMode": {
      "type": "string"
    },
    "orderDeadline": {
      "format": "datetime",
      "type": "string"
    },
    "extendedAngle": {
      "type": "boolean"
    },
    "acquisitionStartDate": {
      "format": "datetime",
      "type": "string"
    },
    "acquisitionEndDate": {
      "format": "datetime",
      "type": "string"
    },
    "incidenceAngle": {
      "format": "float",
      "type": "number"
    },
    "segmentKey": {
      "type": "string"
    },
    "acrossTrackIncidenceAngle": {
      "format": "float",
      "type": "number"
    },
    "maxIncidenceAngle": {
      "format": "float",
      "type": "number"
    }
  }
}

=== api-evangelist/airbus-oneatlas/examples/oneatlas-segment-example.json
{
  "id": "example-id",
  "footprint": "example-footprint",
  "instrumentMode": "example-instrumentMode",
  "orderDeadline": "example-orderDeadline",
  "extendedAngle": true,
  "acquisitionStartDate": "example-acquisitionStartDate",
  "acquisitionEndDate": "example-acquisitionEndDate",
  "incidenceAngle": 1.0,
  "segmentKey": "example-segmentKey",
  "acrossTrackIncidenceAngle": 1.0,
  "maxIncidenceAngle": 1.0
}
